# Generated by Django 4.0 on 2021-12-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
    ]
