# Generated by Django 4.0 on 2022-01-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atracoes", "0002_alter_atracao_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="atracao",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="atracoes/"),
        ),
    ]
