# Generated by Django 4.0 on 2021-12-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=256)),
                ('linha2', models.CharField(blank=True, max_length=256, null=True)),
                ('cidade', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
                ('pais', models.CharField(max_length=128)),
                ('latitulde', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
