# Generated by Django 4.0 on 2021-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_alter_avaliacoes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
