# Generated by Django 4.0 on 2021-12-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pontoturistico_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto Turistico', 'verbose_name_plural': 'Pontos Turisticos'},
        ),
    ]
