# Generated by Django 4.0 on 2022-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_pontoturistico_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="turismo/"),
        ),
    ]
